[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
poem = "3.1.11"
serde = {version = "1.0.219", features = ["derive"]}
store = { path = "../store" }
dotenvy = "0.15.7"
pq = "1.4.3"
